repos:
  - repo: https://github.com/psf/black
    rev: stable # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
